=== davidmoten/xuml-compiler/xuml-tools/trunk/xuml-jaxb/src/main/resources/xuml.xsd
<schema targetNamespace="http://david.moten.org/xuml" xmlns:t="http://david.moten.org/xuml"
	xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<element name="system" type="t:system" />

	<complexType name="system">
		<sequence>
			<element name="class" type="t:class" minOccurs="0" maxOccurs="unbounded" />
			<element name="relationship" type="t:relationship" minOccurs="0"
				maxOccurs="unbounded" />
			<element name="generalization" type="t:generalization"
				minOccurs="0" maxOccurs="unbounded" />
			<element name="association" type="t:association" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="class">
		<complexContent>
			<extension base="t:classWithDomain">
				<sequence>
					<element ref="t:attribute" maxOccurs="unbounded" />
					<element name="operation" type="t:operation" maxOccurs="unbounded"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<element name="attribute" type="t:attribute" />
	<element name="native" substitutionGroup="t:attribute" type="t:nativeAttribute" />
	<element name="referential" substitutionGroup="t:attribute"
		type="t:referentialAttribute" />

	<complexType name="attribute">
		<sequence>
			<element name="identifier" type="t:identifier" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="t:nonBlankString"/>
	</complexType>

	<complexType name="identifier">
		<attribute name="name" type="t:nonBlankString" />
	</complexType>

	<complexType name="nativeAttribute">
		<complexContent>
			<extension base="t:attribute">
				<attribute name="type" type="t:nativeAttributeType" />
				<attribute name="mandatory" type="boolean" use="optional"
					default="true" />
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="nativeAttributeType">
		<restriction base="string">
			<enumeration value="Decimal" />
			<enumeration value="Integer" />
			<enumeration value="Boolean" />
			<enumeration value="Timestamp" />
			<enumeration value="Date" />
			<enumeration value="String" />
			<enumeration value="ArbitraryId" />
		</restriction>
	</simpleType>

	<complexType name="referentialAttribute">
		<complexContent>
			<extension base="t:attribute">
				<attribute name="otherAttribute" type="t:nonBlankString" use="optional"/>
				<attribute name="relationship" type="t:nonBlankString" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="operation">
		<sequence>
			<element name="parameter" type="t:parameter" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="t:nonBlankString" />
		<attribute name="returns" type="t:nonBlankString" use="optional" />
	</complexType>

	<complexType name="parameter">
		<attribute name="name" type="t:nonBlankString" />
		<attribute name="type" type="t:nonBlankString" />
	</complexType>

	<complexType name="relationship">
		<sequence>
			<element name="class1" type="t:relationshipEnd" />
			<element name="class2" type="t:relationshipEnd" />
		</sequence>
		<attribute name="name" type="t:nonBlankString" />
	</complexType>

	<complexType name="relationshipEnd">
		<complexContent>
			<extension base="t:classWithDomain">
				<attribute name="verbClause" type="t:nonBlankString" />
				<attribute name="multiplicity" type="t:multiplicity" />
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="multiplicity">
		<restriction base="string">
			<enumeration value="ZERO_ONE" />
			<enumeration value="ONE" />
			<enumeration value="MANY" />
			<enumeration value="ONE_MANY" />
		</restriction>
	</simpleType>

	<complexType name="generalization">
		<sequence>
			<element name="superClass" type="t:classWithDomain" />
			<element name="class" type="t:classWithDomain" maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="t:nonBlankString" />
	</complexType>

	<complexType name="classWithDomain">
		<attribute name="name" type="t:nonBlankString" />
		<attribute name="domain" type="t:nonBlankString" />
	</complexType>

	<complexType name="association">
		<complexContent>
			<extension base="t:classWithDomain">
				<attribute name="relationshipName" type="t:nonBlankString" />
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="nonBlankString">
		<restriction base="string">
			<pattern value=".*[^\s].*" />
		</restriction>
	</simpleType>

</schema>

=== davidmoten/xuml-compiler/xuml-tools/trunk/xuml-diagrams/src/main/webapp/xuml-sample-1.xml
<domain xmlns="http://david.moten.org/xuml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://david.moten.org/xuml ../../../../xuml-jaxb/src/main/resources/xuml.xsd">

	<class name="Class">
		<attribute name="domain" type="String" />
		<attribute name="name" type="String" />
		<identifier name="I">
			<attribute name="domain" />
			<attribute name="name" />
		</identifier>
	</class>

	<class name="Attribute">
		<attribute name="id" type="ArbitraryId" />
		<attribute name="name" type="String" />
		<attribute name="relationship" type="String" mandatory="false" />
		<identifier name="I">
			<attribute name="id" />
		</identifier>
	</class>
	
	<relationship name="RO1" className1="Class" className2="Attribute" verbClause1="is a member of" verbClause2="has member" multiplicity1="ONE" multiplicity2="ONE_MANY"/>
	

</domain>

=== davidmoten/xuml-compiler/xuml-tools/trunk/xuml-diagrams/src/main/webapp/WEB-INF/classes/xuml-sample-1.xml
<system xmlns="http://david.moten.org/xuml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://david.moten.org/xuml ../../../../xuml-jaxb/src/main/resources/xuml.xsd">

	<class name="Class" domain="xuml">
		<attribute name="Name" type="String" />
		<attribute name="Element" type="String" />
		<attribute name="Cnum" type="String" />
		<identifier name="I">
			<native name="Domain" />
			<native name="Name" />
		</identifier>
	</class>

	<class name="Attribute" domain="xuml">
		<attribute name="id" type="ArbitraryId" />
		<attribute name="name" type="String" />
		<identifier name="I">
			<native name="id" />
		</identifier>
	</class>

	<class name="ReferentialAttribute" domain="xuml">
		<attribute name="id" type="ArbitraryId" />
		<attribute name="name" type="String" />
		<attribute name="relationship" type="String" />
		<identifier name="I">
			<native name="id" />
		</identifier>
	</class>

	<class name="NativeAttribute" domain="xuml">
		<attribute name="id" type="ArbitraryId" />
		<identifier name="I">
			<native name="id" />
		</identifier>
	</class>

	<relationship name="RO1">
		<class1 name="Class" domain="xuml" verbClause="is a member of"
			multiplicity="ONE" />
		<class2 name="Attribute" domain="xuml" verbClause="has member"
			multiplicity="ONE_MANY" />
	</relationship>

	<generalization name="G01">
		<superClass name="Attribute" domain="xuml" />
		<class name="ReferentialAttribute" domain="xuml" />
		<class name="NativeAttribute" domain="xuml" />
	</generalization>

</system>
